Core(Gtk): check if Attributes is null
Added for fixing this error:
```
Exception in Gtk# callback delegate
  Note: Applications can use GLib.ExceptionManager.UnhandledException to handle the exception.
System.NullReferenceException: Object reference not set to an instance of an object.
   at GLib.Value..ctor(Opaque val, String type_name)
   at Gtk.CellRendererText.set_Attributes(AttrList value)
   at Microsoft.Maui.PickerExtensions.UpdateCharacterSpacing(ComboBox nativeView, Double spacing) in /home/geewallet/dependencies/maui/src/Core/src/Platform/Gtk/PickerExtensions.cs:line 53
   at Microsoft.Maui.Handlers.PickerHandler.MapCharacterSpacing(PickerHandler handler, IPicker view) in /home/geewallet/dependencies/maui/src/Core/src/Handlers/Picker/PickerHandler.Gtk.cs:line 108
   at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0.<Add>b__0(IElementHandler h, IElement v) in /home/geewallet/dependencies/maui/src/Core/src/PropertyMapper.cs:line 183
   at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView) in /home/geewallet/dependencies/maui/src/Core/src/PropertyMapper.cs:line 47
   at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView) in /home/geewallet/dependencies/maui/src/Core/src/PropertyMapper.cs:line 82
   at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view) in /home/geewallet/dependencies/maui/src/Core/src/Handlers/Element/ElementHandler.cs:line 79
   at Microsoft.Maui.Handlers.ViewHandler`2.SetVirtualView(IView view) in /home/geewallet/dependencies/maui/src/Core/src/Handlers/View/ViewHandlerOfT.cs:line 55
   at Microsoft.Maui.Handlers.PickerHandler.SetVirtualView(IView view) in /home/geewallet/dependencies/maui/src/Core/src/Handlers/Picker/PickerHandler.Gtk.cs:line 27
   at Microsoft.Maui.Handlers.ViewHandler`2.SetVirtualView(IElement view) in /home/geewallet/dependencies/maui/src/Core/src/Handlers/View/ViewHandlerOfT.cs:line 58
   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler) in /home/geewallet/dependencies/maui/src/Controls/src/Core/HandlerImpl/Element/Element.Impl.cs:line 70
   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value) in /home/geewallet/dependencies/maui/src/Controls/src/Core/HandlerImpl/Element/Element.Impl.cs:line 20
   at Microsoft.Maui.Controls.VisualElement.set_Handler(IViewHandler value) in /home/geewallet/dependencies/maui/src/Controls/src/Core/HandlerImpl/VisualElement/VisualElement.Impl.cs:line 37
   at Microsoft.Maui.HandlerExtensions.ToPlatform(IView view, IMauiContext context) in /home/geewallet/dependencies/maui/src/Core/src/Platform/Gtk/HandlerExtensions.cs:line 22
   at Microsoft.Maui.Handlers.LayoutHandler.SetVirtualView(IView view) in /home/geewallet/dependencies/maui/src/Core/src/Handlers/Layout/LayoutHandler.Gtk.cs:line 41
   at Microsoft.Maui.Handlers.ViewHandler`2.SetVirtualView(IElement view) in /home/geewallet/dependencies/maui/src/Core/src/Handlers/View/ViewHandlerOfT.cs:line 58
   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler) in /home/geewallet/dependencies/maui/src/Controls/src/Core/HandlerImpl/Element/Element.Impl.cs:line 70
   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value) in /home/geewallet/dependencies/maui/src/Controls/src/Core/HandlerImpl/Element/Element.Impl.cs:line 20
   at Microsoft.Maui.Controls.VisualElement.set_Handler(IViewHandler value) in /home/geewallet/dependencies/maui/src/Controls/src/Core/HandlerImpl/VisualElement/VisualElement.Impl.cs:line 37
   at Microsoft.Maui.HandlerExtensions.ToPlatform(IView view, IMauiContext context) in /home/geewallet/dependencies/maui/src/Core/src/Platform/Gtk/HandlerExtensions.cs:line 22
   at Microsoft.Maui.Handlers.LayoutHandler.SetVirtualView(IView view) in /home/geewallet/dependencies/maui/src/Core/src/Handlers/Layout/LayoutHandler.Gtk.cs:line 41
   at Microsoft.Maui.Handlers.ViewHandler`2.SetVirtualView(IElement view) in /home/geewallet/dependencies/maui/src/Core/src/Handlers/View/ViewHandlerOfT.cs:line 58
   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler) in /home/geewallet/dependencies/maui/src/Controls/src/Core/HandlerImpl/Element/Element.Impl.cs:line 70
   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value) in /home/geewallet/dependencies/maui/src/Controls/src/Core/HandlerImpl/Element/Element.Impl.cs:line 20
   at Microsoft.Maui.Controls.VisualElement.set_Handler(IViewHandler value) in /home/geewallet/dependencies/maui/src/Controls/src/Core/HandlerImpl/VisualElement/VisualElement.Impl.cs:line 37
   at Microsoft.Maui.HandlerExtensions.ToPlatform(IView view, IMauiContext context) in /home/geewallet/dependencies/maui/src/Core/src/Platform/Gtk/HandlerExtensions.cs:line 22
   at Microsoft.Maui.Handlers.ContentViewHandler.UpdateContent() in /home/geewallet/dependencies/maui/src/Core/src/Handlers/ContentView/ContentViewHandler.Gtk.cs:line 18
   at Microsoft.Maui.Handlers.ContentViewHandler.MapContent(IContentViewHandler handler, IContentView page) in /home/geewallet/dependencies/maui/src/Core/src/Handlers/ContentView/ContentViewHandler.Gtk.cs:line 25
   at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0.<Add>b__0(IElementHandler h, IElement v) in /home/geewallet/dependencies/maui/src/Core/src/PropertyMapper.cs:line 183
   at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView) in /home/geewallet/dependencies/maui/src/Core/src/PropertyMapper.cs:line 47
   at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView) in /home/geewallet/dependencies/maui/src/Core/src/PropertyMapper.cs:line 82
   at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view) in /home/geewallet/dependencies/maui/src/Core/src/Handlers/Element/ElementHandler.cs:line 79
   at Microsoft.Maui.Handlers.ViewHandler`2.SetVirtualView(IView view) in /home/geewallet/dependencies/maui/src/Core/src/Handlers/View/ViewHandlerOfT.cs:line 55
   at Microsoft.Maui.Handlers.PageHandler.SetVirtualView(IView view) in /home/geewallet/dependencies/maui/src/Core/src/Handlers/Page/PageHandler.Gtk.cs:line 13
   at Microsoft.Maui.Handlers.ViewHandler`2.SetVirtualView(IElement view) in /home/geewallet/dependencies/maui/src/Core/src/Handlers/View/ViewHandlerOfT.cs:line 58
   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler) in /home/geewallet/dependencies/maui/src/Controls/src/Core/HandlerImpl/Element/Element.Impl.cs:line 70
   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value) in /home/geewallet/dependencies/maui/src/Controls/src/Core/HandlerImpl/Element/Element.Impl.cs:line 20
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value) in /home/geewallet/dependencies/maui/src/Controls/src/Core/HandlerImpl/VisualElement/VisualElement.Impl.cs:line 301
   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context) in /home/geewallet/dependencies/maui/src/Core/src/Platform/ElementExtensions.cs:line 101
   at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context) in /home/geewallet/dependencies/maui/src/Core/src/Platform/ElementExtensions.cs:line 132
   at Microsoft.Maui.Platform.NavigationView.RequestNavigation(NavigationRequest request) in /home/geewallet/dependencies/maui/src/Core/src/Platform/Gtk/NavigationView.cs:line 68
   at Microsoft.Maui.Handlers.NavigationViewHandler.RequestNavigation(INavigationViewHandler handler, IStackNavigation navigation, Object request) in /home/geewallet/dependencies/maui/src/Core/src/Handlers/NavigationPage/NavigationViewHandler.Gtk.cs:line 35
   at Microsoft.Maui.CommandMapper`2.<>c__DisplayClass6_0.<Add>b__0(IElementHandler h, IElement v, Object o) in /home/geewallet/dependencies/maui/src/Core/src/CommandMapper.cs:line 89
   at Microsoft.Maui.CommandMapper.InvokeCore(String key, IElementHandler viewHandler, IElement virtualView, Object args) in /home/geewallet/dependencies/maui/src/Core/src/CommandMapper.cs:line 30
   at Microsoft.Maui.CommandMapper.Invoke(IElementHandler viewHandler, IElement virtualView, String property, Object args) in /home/geewallet/dependencies/maui/src/Core/src/CommandMapper.cs:line 48
   at Microsoft.Maui.Handlers.ElementHandler.Invoke(String command, Object args) in /home/geewallet/dependencies/maui/src/Core/src/Handlers/Element/ElementHandler.cs:line 95
   at Microsoft.Maui.Controls.NavigationPage.Microsoft.Maui.IStackNavigation.RequestNavigation(NavigationRequest eventArgs) in /home/geewallet/dependencies/maui/src/Controls/src/Core/HandlerImpl/NavigationPage/NavigationPage.Impl.cs:line 43
   at Microsoft.Maui.Controls.NavigationPage.SendHandlerUpdateAsync(Boolean animated, Action processStackChanges, Action firePostNavigatingEvents, Action fireNavigatedEvents) in /home/geewallet/dependencies/maui/src/Controls/src/Core/HandlerImpl/NavigationPage/NavigationPage.Impl.cs:line 204
   at Microsoft.Maui.TaskExtensions.FireAndForget(Task task, Action`1 errorCallback) in /home/geewallet/dependencies/maui/src/Core/src/TaskExtensions.cs:line 36
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at GLib.GLibSynchronizationContext.<>c__DisplayClass0_0.<Post>b__0()
   at GLib.GLibSynchronizationContext.<>c__DisplayClass2_0.<PostAction>b__0()
   at GLib.Idle.IdleProxy.Handler()
   at GLib.ExceptionManager.RaiseUnhandledException(Exception e, Boolean is_terminal)
   at GLib.Idle.IdleProxy.Handler()
   at GLib.Application.Run(String program_name, String[] args)
   at GLib.Application.Run()
   at Microsoft.Maui.MauiGtkApplication.Launch(EventArgs args) in /home/geewallet/dependencies/maui/src/Core/src/Platform/Gtk/MauiGtkApplication.cs:line 127
   at Microsoft.Maui.MauiGtkApplication.Run(String[] args) in /home/geewallet/dependencies/maui/src/Core/src/Platform/Gtk/MauiGtkApplication.cs:line 40
   at GWallet.Frontend.Maui.Program.main(String[] _args) in /home/geewallet/src/GWallet.Frontend.Maui/Platforms/Gtk/Program.fs:line 14
```